format = "$directory $character "

right_format = "$git_branch$git_status$time"

add_newline = false

[directory]
truncate_to_repo = true
truncation_length = 10
format = "[$path]($style)"
style = "bold blue"
repo_root_style = "bold yellow"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[➜](bold blue)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold yellow"

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%H:%M"
style = "bold cyan"
